- name: set host ips is /etc/hosts file
  hosts: all
  tasks:
  - name: update host file
    blockinfile:
      path: /etc/hosts
      backup: yes
      block: |
       {{item.ip}} {{item.name}}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    with_items:
      - {name: web1,ip: 10.1.10.252}
      - {name: web2,ip: 10.1.20.121}
      - {name: App1,ip: 10.1.10.6}
      - {name: App2,ip: 10.1.20.40}
      - {name: RQM01,ip: 10.1.10.138}
      - {name: MC01,ip: 10.1.10.242}
      - {name: MC01,ip: 10.1.10.242}

